project:
  type: website
  output-dir: docs
  
website:
  title: "Michelle Trim Professional Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:

      - icon: github
        href: https://github.com/MDTrim/website2
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Michelle Trim"

format:
  html:
    theme: cerulean
    toc: true

editor: source

