---
title: "Projects"
---

## Current Project

<b>Understanding access to CS-A AP Exams in Massachusetts </b>

This project involves exploring and analyzing the data provided by the State of Massachusetts on high school AP exams completed in a given school year, across the state. Data is reported by school district, and when there are 10 or tests taken, the data are broken down into scores. Other information includes the size of the senior cohort and tests taken by demographic features such as race and gender. 

In my analysis, I have tried to determine if there is a relationship between school district wealth and access to and success on CS A AP exams. Because computer science is a field concerned with broadening its representation of various types of identity, and because UMass is a state Land Grant institution with a responsibility to educate our state's citizens, I wanted to know if there seemed to be a way that the AP exam is creating more opportunities for those from wealthier districts. 

In my statistical analysis I was unable to find a meaningful correlation in the data provided on the State's Education website.  But, by examining just the top 20 districts in terms of number of exams taken, and correlating those districts with the median home price, I was able to determine that a disproportionate number of CS-A Exams are taken in districts with very high (at or above $1 million) median home values.


<a href = "project_AP.html">Here are more details about this project. </a>